package nus_iss.LAPS.model;

import java.time.LocalDate;
import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

/**
 *  Represents a leave application submitted by an employee.
 *  Contains details about the leave type, duration, reason, and approval status.
 *
 *  Author: Htet Nandar(Grace)
 *  Created on: 11/04/2026
 */
@Entity
@Table(name = "leave_application")
public class LeaveApplication {
	
 /** Unique identifier for this leave application, auto-generated by the database. */
 @Id
 @GeneratedValue(strategy = GenerationType.IDENTITY)
 @Column(name = "leaveapplication_id")
 private Long leaveApplicationId;

 /** The employee who submitted this leave application (required). */
 @ManyToOne(fetch = FetchType.LAZY)
 @JoinColumn(name = "emp_id", nullable = false)
 private Employee employee;

 /** The type of leave being requested (e.g., annual, medical, personal). */
 @ManyToOne(fetch = FetchType.LAZY)
 @JoinColumn(name = "leavetype_id", nullable = false)
 private LeaveType leaveType;

 /** The first day of the requested leave period (required). */
 @Column(name = "start_date", nullable = false)
 private LocalDate startDate;

 /** The last day of the requested leave period (required). */
 @Column(name = "end_date", nullable = false)
 private LocalDate endDate;

 /** Total number of days requested for this leave (required). */
 @Column(name = "duration_days", nullable = false)
 private Double durationDays;

    /** Why the employee is taking leave (mandatory). */
 @Column(name = "reason", nullable = false, columnDefinition = "TEXT")
 private String reason;

    /**
     * Work dissemination — who will cover the employee's duties during absence.
     * Optional, but encouraged for longer leave periods.
     */
    @Column(name = "work_dissemination", columnDefinition = "TEXT")
    private String workDissemination;

    /**
     * Flag indicating whether the employee will be overseas during leave.
     * When true, contactDetails is mandatory (enforced in service layer).
     */
    @Column(name = "is_overseas", nullable = false)
    private Boolean isOverseas = false;

    /**
     * Contact details while on leave — required only for overseas trips.
     * May contain phone number, address, or other reachable contact info.
     */
    @Column(name = "contact_details", columnDefinition = "TEXT")
    private String contactDetails;

 /** Current status of this leave application (PENDING, APPROVED, REJECTED, CANCELLED). */
 @Enumerated(EnumType.STRING)
 @Column(name = "status", nullable = false)
 private LeaveStatus status = LeaveStatus.PENDING;

 /** The manager or approver who processed this leave application. Null until approved/rejected. */
 @ManyToOne(fetch = FetchType.LAZY)
 @JoinColumn(name = "approver_by", referencedColumnName = "emp_id")
 private Employee approvedBy;

 /** Employee ID (emp_id) of the user who created this application. */
 @Column(name = "created_by")
    private String createdBy;

    /** Timestamp when this leave application was created (auto-set on persistence). */
    @Column(name = "created_when")
    private LocalDateTime createdWhen;

    /** Employee ID (emp_id) of the user who last updated this application. */
    @Column(name = "updated_by")
    private String updatedBy;

    /** Timestamp when this leave application was last modified (auto-updated on changes). */
    @Column(name = "updated_when")
    private LocalDateTime updatedWhen;
    
    // Lifecycle hooks
    /**
     * Automatically called before the entity is persisted (saved) to the database.
     * Initializes createdWhen and updatedWhen timestamps, and ensures status defaults to PENDING.
     */
    @PrePersist
    protected void onCreate() {
        this.createdWhen = LocalDateTime.now();
        this.updatedWhen = LocalDateTime.now();
        if (this.status == null) {
            this.status = LeaveStatus.PENDING;
        }
    }

    /**
     * Automatically called before the entity is updated in the database.
     * Updates the updatedWhen timestamp to reflect the current modification time.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedWhen = LocalDateTime.now();
    }
    
    /**
     * Default no-argument constructor. Required by JPA for entity instantiation.
     */
    public LeaveApplication() {}

    /**
     * @param employee
     * @param leaveType
     * @param startDate
     * @param endDate
     * @param durationDays
     * @param reason
     * @param workDissemination
     * @param isOverseas
     * @param contactDetails
     */
    public LeaveApplication(Employee employee, LeaveType leaveType,
                            LocalDate startDate, LocalDate endDate,
                            Double durationDays, String reason,
                            String workDissemination, Boolean isOverseas,
                            String contactDetails) {
  this.employee = employee;
  this.leaveType = leaveType;
  this.startDate = startDate;
  this.endDate = endDate;
  this.durationDays = durationDays;
  this.reason = reason;
        this.workDissemination = workDissemination;
        this.isOverseas       = isOverseas != null ? isOverseas : false;
        this.contactDetails   = contactDetails;
  this.status = LeaveStatus.PENDING;
 }

    /**
     * Retrieves the unique identifier of this leave application.
     * @return the leave application ID
     */
 public Long getLeaveApplicationId() {
  return leaveApplicationId;
 }

    /**
     * Sets the unique identifier for this leave application.
     * @param leaveApplicationId the leave application ID to set
     */
 public void setLeaveApplicationId(Long leaveApplicationId) {
  this.leaveApplicationId = leaveApplicationId;
 }

    /**
     * Retrieves the employee who submitted this leave application.
     * @return the Employee object associated with this application
     */
 public Employee getEmployee() {
  return employee;
 }

    /**
     * Sets the employee for this leave application.
     * @param employee the Employee submitting the application
     */
 public void setEmployee(Employee employee) {
  this.employee = employee;
 }

    /**
     * Retrieves the type of leave requested.
     * @return the LeaveType object (e.g., annual, medical, personal)
     */
 public LeaveType getLeaveType() {
  return leaveType;
 }

    /**
     * Sets the type of leave for this application.
     * @param leaveType the LeaveType to set
     */
 public void setLeaveType(LeaveType leaveType) {
  this.leaveType = leaveType;
 }

    /**
     * Retrieves the start date of the leave period.
     * @return the start date (LocalDate)
     */
 public LocalDate getStartDate() {
  return startDate;
 }

    /**
     * Sets the start date for this leave period.
     * @param startDate the start date to set
     */
 public void setStartDate(LocalDate startDate) {
  this.startDate = startDate;
 }

    /**
     * Retrieves the end date of the leave period.
     * @return the end date (LocalDate)
     */
 public LocalDate getEndDate() {
  return endDate;
 }

    /**
     * Sets the end date for this leave period.
     * @param endDate the end date to set
     */
 public void setEndDate(LocalDate endDate) {
  this.endDate = endDate;
 }

    /**
     * Retrieves the total number of days requested for this leave.
     * @return the duration in days (Double)
     */
 public Double getDurationDays() {
  return durationDays;
 }

    /**
     * Sets the duration in days for this leave application.
     * @param durationDays the number of days to set
     */
 public void setDurationDays(Double durationDays) {
  this.durationDays = durationDays;
 }

    /**
     * Retrieves the reason for this leave application.
     * @return the leave reason as a string
     */
 public String getReason() {
  return reason;
 }

    /**
     * Sets the reason for this leave application.
     * @param reason the reason to set
     */
 public void setReason(String reason) {
  this.reason = reason;
 }

    /**
     * Retrieves the current status of this leave application.
     * @return the LeaveStatus (PENDING, APPROVED, REJECTED, or CANCELLED)
     */
 public LeaveStatus getStatus() {
  return status;
 }

    /**
     * Sets the status of this leave application.
     * @param status the LeaveStatus to set
     */
 public void setStatus(LeaveStatus status) {
  this.status = status;
 }

    /**
     * Retrieves the manager or approver who processed this application.
     * @return the Employee who approved/rejected this application, or null if pending
     */
 public Employee getApprovedBy() {
  return approvedBy;
 }

    /**
     * Sets the employee who approves/rejects this leave application.
     * @param approvedBy the Employee approver to set
     */
 public void setApprovedBy(Employee approvedBy) {
  this.approvedBy = approvedBy;
 }

    /**
     * Retrieves the employee ID of the user who created this application.
     * @return the creator's employee ID (emp_id)
     */
 public String getCreatedBy() {
  return createdBy;
 }

    /**
     * Sets the employee ID of the user who created this application.
     * @param createdBy the creator's employee ID to set
     */
 public void setCreatedBy(String createdBy) {
  this.createdBy = createdBy;
 }

    /**
     * Retrieves the timestamp when this application was created.
     * @return the creation timestamp (LocalDateTime)
     */
 public LocalDateTime getCreatedWhen() {
  return createdWhen;
 }

    /**
     * Sets the creation timestamp for this application.
     * @param createdWhen the creation timestamp to set
     */
 public void setCreatedWhen(LocalDateTime createdWhen) {
  this.createdWhen = createdWhen;
 }

    /**
     * Retrieves the employee ID of the user who last updated this application.
     * @return the last updater's employee ID (emp_id)
     */
 public String getUpdatedBy() {
  return updatedBy;
 }

    /**
     * Sets the employee ID of the user who last updated this application.
     * @param updatedBy the updater's employee ID to set
     */
 public void setUpdatedBy(String updatedBy) {
  this.updatedBy = updatedBy;
 }

    /**
     * Retrieves the timestamp when this application was last modified.
     * @return the last update timestamp (LocalDateTime)
     */
 public LocalDateTime getUpdatedWhen() {
  return updatedWhen;
 }

    /**
     * Sets the last update timestamp for this application.
     * @param updatedWhen the last update timestamp to set
     */
 public void setUpdatedWhen(LocalDateTime updatedWhen) {
  this.updatedWhen = updatedWhen;
 }

    /**
     * Retrieves the work dissemination details for this leave.
     * @return the person/details covering the employee's duties (optional)
     */
    public String getWorkDissemination() {
        return workDissemination;
    }

    /**
     * Sets the work dissemination details for this leave.
     * @param workDissemination the details of who will cover duties
     */
    public void setWorkDissemination(String workDissemination) {
        this.workDissemination = workDissemination;
    }

    /**
     * Retrieves the contact details while on leave.
     * @return the contact information (required only for overseas leave)
     */
    public String getContactDetails() {
        return contactDetails;
    }

    /**
     * Sets the contact details while on leave.
     * @param contactDetails the contact information to set
     */
    public void setContactDetails(String contactDetails) {
        this.contactDetails = contactDetails;
    }

    /**
     * Checks if the employee will be overseas during this leave.
     * @return true if the employee will be overseas, false otherwise
     */
    public Boolean getIsOverseas() {
        return isOverseas;
    }

    /**
     * Sets whether the employee will be overseas during this leave.
     * @param overseas true if the employee will be overseas, false otherwise
     */
    public void setOverseas(Boolean overseas) {
        isOverseas = overseas;
    }

    /**
     * Returns a string representation of this leave application.
     * 
     * Provides a summary of key leave application details including:
     * ID, leave type, start/end dates, duration, and current status.
     * Employee reference is excluded to avoid circular dependencies in output.
     * 
     * @return a formatted string containing the leave application's key attributes
     */
    @Override
 public String toString() {
        return "LeaveApplication{" +
                "leaveApplicationId=" + leaveApplicationId +
               // ", employee=" + (employee != null ? employee.getEmpId() : null) +
                ", leaveType=" + (leaveType != null ? leaveType.getLeaveTypeId() : null) +
                ", startDate=" + startDate +
                ", endDate=" + endDate +
                ", durationDays=" + durationDays +
                ", status=" + status +
                '}';
    }
    
}